// Imports the TypeScript type for Next.js metadata to ensure type safety
import type { Metadata } from "next";
// Imports specific Google Fonts directly through Next.js's optimized font loader
import { Geist, Geist_Mono } from "next/font/google";
// Imports your global styles (where your Tailwind directives live)
import "./globals.css";


// Defines the default <head> tags for your entire application (great for SEO!).
// Next.js automatically injects this into the HTML it generates.
export const metadata: Metadata = {
  title: "Analytics-Dashboard", // What shows up in the browser tab
  description: "Generated by create next app", // Meta description for search engines
};

// The main layout component. 
// It uses TypeScript to strictly define that 'children' must be a valid React Node.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // The mandatory root HTML tag
    <html lang="en">
      {/* The body tag applies the CSS variables for the fonts we set up above.
        The 'antialiased' class is a Tailwind utility that makes the font rendering look smoother.
      */}
      <body
        
      >
        {/* This is where your page.tsx content will be injected! */}
        {children}
      </body>
    </html>
  );
}